# -*- coding: utf-8 -*-
"""law_gpt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16EpJneaqAgz-ekE2XIqGnLoQ-c5Z1RUq
"""

!pip install cohere tiktoken
!pip install h11 httpcore httpx openai

!pip install langchain
!pip install openai

import os
os.environ["OPENAI_API_KEY"] = "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"
os.environ["SERPAPI_API_KEY"] = "b622f6c064907868590df96fc4c504a55a75921b7fd3b61466c860318a3005d3"

from langchain.llms import OpenAI

llm = OpenAI(temperature=0.9)

from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

prompt = PromptTemplate(input_variables=["query"], template="Answer in terms of Indian law {query}")
chain = LLMChain(llm=llm, prompt=prompt, verbose=True)

print(chain.run("education"))