# -*- coding: utf-8 -*-
"""QueryBOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOd70T_JVb2ZL1daxNU2V-OJw0tskmSc
"""

!pip install langchain

!pip install openai

!pip install google-search-results

from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.llms import OpenAI
import os

os.environ["OPENAI_API_KEY"] = "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"
os.environ["SERPAPI_API_KEY"] = "b622f6c064907868590df96fc4c504a55a75921b7fd3b61466c860318a3005d3"

llm = OpenAI(temperature=0.1)
tools = load_tools(["serpapi"])
agent = initialize_agent(tools, llm, agents="zero-shot-react-description")

agent.run("Write a c++ code to add two numbers")